apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sscs-mcp-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sscs-mcp-server 
  name: sscs-mcp-server
spec:
  ports:
  - port: 8000 
    targetPort: 8000 
  selector:
    app.kubernetes.io/instance: sscs-mcp-server 
